using System.Windows;
using System.Windows.Threading;
using System.Windows.Media;

namespace OmniZenNotes
{
    // @see Properties/Settings.Settings and Settings.Designer.cs for <auto-generated> files
    // Visual Studio 2019 was used to create the above intial files, but can be edited OK by hand
    
    public partial class NoteViewer : Window
    {
        DispatcherTimer AutoSaveTimer;
        
        // Loaded from App Settings located @ C:\User\{User}\AppData\Local\OmniZenNotes\OmniZenNote.exe_...
        void LoadSettings() {
            try {
                // Restore the Window State (minimized gets converted to be Normal to avoid user not seeing it)
                WindowState = WindowState == WindowState.Minimized ? WindowState.Normal : WindowState;

                // Use App Defaults for Note if not UX Settings exist
                if (VM.Note.UXSettings is null) {
                    // Restore Window position and size from user settings save of last session
                    // RND: Use of CalculatePopupWindowPosition function (winuser.h) to keep window on screen
                    if (S.Default?.RestoreBounds is Rect restoreBounds) {
                        Left = restoreBounds.Left; Top = restoreBounds.Top;
                        Width = restoreBounds.Width; Height = restoreBounds.Height;
                    }

                    SetFont(S.Default.Font, S.Default.FontSize, S.Default.FontColor, FontStyle, updateUXSettings: false);
                    uxColorPicker.SelectedColor = S.Default.BackgroundColor;
                    SetBackgroundColor(S.Default.BackgroundColor, updateUXSettings: false);
                    uxOptionsExpander.IsExpanded = S.Default.OptionsExpanded;
                    Topmost = S.Default.Topmost;
                }

                // Auto Save Settings
                if (S.Default.AutoSave is int seconds && seconds > 0) {
                    AutoSaveTimer = new ();
                    AutoSaveTimer.Tick += new ((sender, e) => Save(saveAsync: true));
                    AutoSaveTimer.Interval = TimeSpan.FromSeconds(seconds);
                    AutoSaveTimer.Start();
                }
            } catch {
                Width = 320; Height = 320;
                WindowStartupLocation = WindowStartupLocation.CenterScreen;
            }

            LoadUXSettings();
            if (uxRichTextBox.Document.Background is SolidColorBrush scba) {
                uxColorPicker.SelectedColor = scba.Color;
            }
        }

        // Restore the Note specific settings (which override the App level settings)
        void LoadUXSettings() {

            // Restore the Window State (minimized gets converted to be Normal to avoid user not seeing it)
            SetFont(VM.Note.UXSettings.FontFamily, VM.Note.UXSettings.FontSize, VM.Note.UXSettings.FontColor, FontStyle);
            uxColorPicker.SelectedColor = VM.Note.UXSettings.BackgroundColor;
            SetBackgroundColor(VM.Note.UXSettings.BackgroundColor);
            uxOptionsExpander.IsExpanded = VM.Note.UXSettings.OptionsExpanded;

            RTBFB.IsEnabled = !VM.Note.UXSettings.FormatBar;
            OnToggleFormatBarCommand(null, null); 
            uxRichTextBox.SpellCheck.IsEnabled = !VM.Note.UXSettings.SpellCheck;
            OnToggleSpellCheckCommand(null, null);
            Topmost = VM.Note.UXSettings.Topmost;
            UpdatePinTabUX();

            uxToolBar.LayoutTransform = new ScaleTransform(VM.Note.UXSettings.ToolBarScale, VM.Note.UXSettings.ToolBarScale);
            Visibility = VM.Note.UXSettings.Visibility;

            if (VM.Note.UXSettings.RestoreBounds is Rect rb && double.IsFinite(rb.Left) && double.IsFinite(rb.Top)) {
                Width = rb.Width; Height = rb.Height;
                if (rb.Top != 0 && rb.Left != 0) {
                    Top = rb.Top; Left = rb.Left; 
                } else
                    WindowStartupLocation = WindowStartupLocation.CenterScreen;
            }
            
            // Use current and saved monitor information to compare Screen bounds for changes
            // If screen no longer exists, (ie multi monitor configuration changed), place at CenterScreen
            if (U.Graphics.GetScreen(VM.Note.UXSettings.MonitorInfo) is System.Windows.Forms.Screen curScreen) {
                try {
                    var savedScreen = U.Json.GetObjectFromJson<dynamic>(VM.Note.UXSettings.MonitorInfo);
                    // If screen size bounds has changed, try to account for the new layout
                    // Bounds is a rectangle stored as X, Y, Width, Height string values
                    string boundsString = savedScreen.Bounds.Value as string;
                    System.Drawing.Rectangle savedBounds = (System.Drawing.Rectangle)new System.Drawing.RectangleConverter().ConvertFromString(boundsString);
                    if (curScreen.Bounds != savedBounds) {
                        Top += curScreen.Bounds.Top - savedBounds.Top;
                        Left += curScreen.Bounds.Left - savedBounds.Left;
                    }
                } catch {
                    WindowStartupLocation = WindowStartupLocation.CenterScreen;
                }
            } else {
                WindowStartupLocation = WindowStartupLocation.CenterScreen;
            }
        }

        void SaveUXSettings() {
            // Save the Note specific settings (which override the App level settings)
            if (VM.Note != null) {
                VM.Note.UXSettings ??= new ();
                VM.Note.UXSettings.RestoreBounds = RestoreBounds;
                VM.Note.UXSettings.WindowState = WindowState;
                VM.Note.UXSettings.FontFamily = uxRichTextBox.FontFamily;
                VM.Note.UXSettings.FontSize = uxRichTextBox.FontSize;
                if (uxRichTextBox.Foreground is SolidColorBrush fgscb) {
                    VM.Note.UXSettings.FontColor = fgscb.Color;
                }
                if (uxRichTextBox.Document.Background is SolidColorBrush scba) {
                    VM.Note.UXSettings.BackgroundColor = scba.Color;
                }
                VM.Note.UXSettings.OptionsExpanded = uxOptionsExpander.IsExpanded;
                VM.Note.UXSettings.FormatBar = RTBFB.IsEnabled;
                VM.Note.UXSettings.SpellCheck = uxRichTextBox.SpellCheck.IsEnabled;
                VM.Note.UXSettings.Topmost = Topmost;
                if( uxToolBar.LayoutTransform is ScaleTransform st) {
                    VM.Note.UXSettings.ToolBarScale = st.ScaleX;
                }
                VM.Note.UXSettings.Visibility = Visibility;
                VM.Note.UXSettings.ZOrder = 1;
                VM.Note.UXSettings.MonitorInfo = U.Graphics.GetMonitorInfo(this);
            }
        }

        internal void SaveSettings() {

            SaveUXSettings();

            // Save the App wide default settings:
            S.Default.RestoreBounds = RestoreBounds;
            S.Default.WindowState = WindowState;
            S.Default.Font = FontFamily;
            S.Default.FontSize = FontSize;

            if (uxRichTextBox.Foreground is SolidColorBrush fgscb2)
            {
                S.Default.FontColor = fgscb2.Color;
            }

            if (uxRichTextBox.Document.Background is SolidColorBrush scb)
            {
                S.Default.BackgroundColor = scb.Color;
            }

            S.Default.OptionsExpanded = uxOptionsExpander.IsExpanded;
            S.Default.Topmost = Topmost;

            S.Default.Save();
        }
    }
}